name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12.3"
        environment-file: ""  # No usamos environment.yml

    - name: Create and activate Conda environment
      run: |
        conda create --name myenv python=3.10 -y
        echo "CONDA_ENV=myenv" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        conda install -y flake8 pytest pytest-cov psycopg2

    - name: Lint with flake8
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest and collect coverage
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: backend/coverage-go.out
          fail_ci_if_error: true
          verbose: true
